apiVersion: v1
appVersion: 8.14.3
description: Official Elastic helm chart for Logstash
home: https://github.com/elastic/helm-charts
icon: https://helm.elastic.co/icons/logstash.png
maintainers:
  - email: helm-charts@elastic.co
    name: Elastic
name: logstash
sources:
  - https://github.com/elastic/logstash
version: 8.14.3
